In [1]:
import numpy as np

In [2]:
a = np.random.randint(-5, 5, (5, ))
b = np.random.randint(-5, 5, (5, ))
print("a: ", a)
print("b: ", b, '\n')
print("a + b: ", a + b)

a:  [ 3  0  0 -5 -2]
b:  [-5 -1  0 -3  1] 

a + b:  [-2 -1  0 -8 -1]


In [3]:
a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))
print("a: ", a)
print("b: ", b, '\n')
print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)
print("a // b: ", a // b)
print("a % b: ", a % b)
print("a ** b: ", a ** b)

a:  [1 1 3 2 3]
b:  [3 4 2 1 3] 

a + b:  [4 5 5 3 6]
a - b:  [-2 -3  1  1  0]
a * b:  [3 4 6 2 9]
a / b:  [0.33333333 0.25       1.5        2.         1.        ]
a // b:  [0 0 1 2 1]
a % b:  [1 1 1 0 0]
a ** b:  [ 1  1  9  2 27]


In [4]:

a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))
print("a: ", a)
print("b: ", b, '\n')
print("a > b: ", a > b)
print("a >= b: ", a >= b)
print("a < b: ", a < b)
print("a <= b: ", a <= b)
print("a == b: ", a == b)
print("a != b: ", a != b)


a:  [2 1 3 2 1]
b:  [4 2 2 2 4] 

a > b:  [False False  True False False]
a >= b:  [False False  True  True False]
a < b:  [ True  True False False  True]
a <= b:  [ True  True False  True  True]
a == b:  [False False False  True False]
a != b:  [ True  True  True False  True]


In [5]:

a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))
print("a: ", a)
print("b: ", b, '\n')

print("a + b: ", a.__add__(b))
print("a - b: ", a.__sub__(b))
print("a * b: ", a.__mul__(b))
print("a / b: ", a.__truediv__(b))
print("a // b: ", a.__floordiv__(b))
print("a % b: ", a.__mod__(b))
print("a ** b: ", a.__pow__(b))


a:  [2 3 2 2 2]
b:  [3 1 1 2 1] 

a + b:  [5 4 3 4 3]
a - b:  [-1  2  1  0  1]
a * b:  [6 3 2 4 2]
a / b:  [0.66666667 3.         2.         1.         2.        ]
a // b:  [0 3 2 1 2]
a % b:  [2 0 0 0 0]
a ** b:  [8 3 2 4 2]


In [6]:

M = np.random.randint(1, 5, (2, 3))
N = np.random.randint(1, 5, (2, 3))

print("M: \n", M)
print("N: \n", N, '\n')
print("M + N: \n", M + N)
print("M - N: \n", M - N)
print("M > N: \n", M > N)
print("M >= N: \n", M >= N)

M: 
 [[1 1 4]
 [4 2 3]]
N: 
 [[1 1 1]
 [3 3 2]] 

M + N: 
 [[2 2 5]
 [7 5 5]]
M - N: 
 [[ 0  0  3]
 [ 1 -1  1]]
M > N: 
 [[False False  True]
 [ True False  True]]
M >= N: 
 [[ True  True  True]
 [ True False  True]]


In [7]:
a = np.arange(5)
mask = np.array([0, 1, 0, 1, 0])
print("input: ", a)
print("mask: ", mask)
print("output: ", a*b)

input:  [0 1 2 3 4]
mask:  [0 1 0 1 0]
output:  [0 1 2 6 4]


In [8]:

a = np.arange(1, 5).reshape((2, 2))
mask = np.array([[0, 0], [1, 0]])
print("input: \n", a)
print("mask: \n", mask)
print("output: \n", a*mask)

input: 
 [[1 2]
 [3 4]]
mask: 
 [[0 0]
 [1 0]]
output: 
 [[0 0]
 [3 0]]


In [9]:
A = np.arange(9).reshape(3, 3)
B = 10*np.arange(3).reshape((-1, 3))
C = A + B


print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(1, 3)
[[ 0 10 20]]

A + B: 2/(3, 3)
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]]


In [10]:
A = np.arange(9).reshape(3, 3)
B = 10*np.arange(3).reshape((3, -1))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(3, 1)
[[ 0]
 [10]
 [20]]

A + B: 2/(3, 3)
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


In [11]:
A = np.arange(3).reshape((3, -1))
B = 10*np.arange(3).reshape((-1, 3))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 1)
[[0]
 [1]
 [2]]
B: 2/(1, 3)
[[ 0 10 20]]

A + B: 2/(3, 3)
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]


In [12]:
A = np.arange(18).reshape((2, 3, 3))
B = 10*np.arange(9).reshape((1, 3, 3))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(1, 3, 3)
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]]

A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]]


In [13]:
A = np.arange(18).reshape((2, 3, 3))
B = 10*np.arange(6).reshape((2, 1, 3))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 1, 3)
[[[ 0 10 20]]

 [[30 40 50]]]

A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]


In [14]:
A = np.arange(18).reshape((2, 3, 3))
B = 10*np.arange(6).reshape((2, 3, 1))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]

A + B: 3/(2, 3, 3)
[[[ 0  1  2]
  [13 14 15]
  [26 27 28]]

 [[39 40 41]
  [52 53 54]
  [65 66 67]]]


In [15]:
A = np.arange(6).reshape((2, 1, 3))
B = 10*np.arange(6).reshape((2, 3, 1))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 1, 3)
[[[0 1 2]]

 [[3 4 5]]]
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]

A + B: 3/(2, 3, 3)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[33 34 35]
  [43 44 45]
  [53 54 55]]]


In [16]:
a = np.array(3)
u = np.arange(5)
print("shapes: {}/{}".format(a.shape, u.shape))
print("a: ", a)
print("u: ", u, '\n')

shapes: ()/(5,)
a:  3
u:  [0 1 2 3 4] 



In [17]:
a = np.array(3)
u = np.arange(1, 5)
shapes = "shapes: {}/{}"
print(shapes.format(a.shape,u.shape))
print("a: ", a)
print("u: ", u, '\n')

print("a + u: ", a + u)
print("a - u: ", a - u)
print("a * u: ", a * u)
print("a / u: ", a / u)
print("a // u: ", a // u)
print("a % u: ", a % u)
print("a ** u: ", a ** u,'\n')
print("a > u: ", a > u)
print("a >= u: ", a >= u)
print("a < u: ", a < u)
print("a <= u: ", a <= u)
print("a == u: ", a == u)
print("a != u: ", a != u)

shapes: ()/(4,)
a:  3
u:  [1 2 3 4] 

a + u:  [4 5 6 7]
a - u:  [ 2  1  0 -1]
a * u:  [ 3  6  9 12]
a / u:  [3.   1.5  1.   0.75]
a // u:  [3 1 1 0]
a % u:  [0 1 0 3]
a ** u:  [ 3  9 27 81] 

a > u:  [ True  True False False]
a >= u:  [ True  True  True False]
a < u:  [False False False  True]
a <= u:  [False False  True  True]
a == u:  [False False  True False]
a != u:  [ True  True False  True]


In [18]:
A = np.array([10, 20])
B = np.arange(6).reshape((3, 2))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))


A: 1/(2,)
[10 20]
B: 1/(3, 2)
[[0 1]
 [2 3]
 [4 5]]

A + B: 1/(3, 2)
[[10 21]
 [12 23]
 [14 25]]


In [19]:
A = np.arange(2*3*4).reshape((2, 3, 4))
B = 10*np.arange(3*4).reshape((3, 4))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 3/(3, 4)
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]

A + B: 3/(2, 3, 4)
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]]


In [20]:

A = np.arange(2*3*4).reshape((2, 3, 4))
B = 10*np.arange(4)
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))


A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 3/(4,)
[ 0 10 20 30]

A + B: 3/(2, 3, 4)
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]]


In [21]:

a = np.arange(10)
print(f"ndarray: \n{a}\n")
a[-1] : 9
a[-2] : 8
print("a[0] : ", a[0])
print("a[2] : ", a[2])

print("a[-1] : ", a[-1]) # the last element
print("a[-2] : ", a[-2]) # the 2nd last element


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0] :  0
a[2] :  2
a[-1] :  9
a[-2] :  8


In [22]:

a = np.arange(5)
print(f"ndarray: \n{a}\n")

for data in a:
    print(data)

ndarray: 
[0 1 2 3 4]

0
1
2
3
4


In [23]:

a = np.arange(10)
print(f"ndarray: \n{a}\n")

print("a[0:3] : ", a[0:3])
print("a[3:7] : ", a[3:7])
print("a[5:-1] : ", a[5:-1])


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0:3] :  [0 1 2]
a[3:7] :  [3 4 5 6]
a[5:-1] :  [5 6 7 8]


In [24]:

a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[2:] : ", a[2:])
print("a[-2:] : ", a[-2:]) # the last two elements
print("a[:5] : ", a[:5])
print("a[:-3] : ", a[:-3])
print("a[:] : ", a[:])


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:] :  [2 3 4 5 6 7 8 9]
a[-2:] :  [8 9]
a[:5] :  [0 1 2 3 4]
a[:-3] :  [0 1 2 3 4 5 6]
a[:] :  [0 1 2 3 4 5 6 7 8 9]


In [25]:

a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[2:7:2] : ", a[2:7:2])
print("a[::3] : ", a[::3])


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:7:2] :  [2 4 6]
a[::3] :  [0 3 6 9]


In [26]:

a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[7:2:-1] : ", a[7:2:-1])
print("a[::-1] : ", a[::-1])
print("a[8:3:-2] : ", a[8:3:-2])
print("a[::-3] : ", a[::-3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[7:2:-1] :  [7 6 5 4 3]
a[::-1] :  [9 8 7 6 5 4 3 2 1 0]
a[8:3:-2] :  [8 6 4]
a[::-3] :  [9 6 3 0]


In [27]:

a = np.arange(10)
indices = np.array([0, 3, 6, -1])
print(f"ndarray: \n{a}\n")
print(a[[0, 3, 6, -1]])
print(a[indices])
print(a[a%3==0])


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[0 3 6 9]
[0 3 6 9]
[0 3 6 9]


In [28]:

a = list(range(1, 11))
print(a)

a = np.arange(1, 11)
print(a)

for data_idx in range(5):
    a[data_idx] = 0
print(a)

a[:5] = 0
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  0  0  0  0  6  7  8  9 10]
[ 0  0  0  0  0  6  7  8  9 10]


In [29]:

a = np.arange(1, 11)
print(a)

a[::2] = 200
print(a)

a[5:-1:3] = 300
print(a)


[ 1  2  3  4  5  6  7  8  9 10]
[200   2 200   4 200   6 200   8 200  10]
[200   2 200   4 200 300 200   8 300  10]


In [30]:

a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

print(a[0])
print(a[1])
print(a[2])
print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[0][2])
print(a[2][0], a[2][1], a[2][2])

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
0 1 2
3 4 2
6 7 8


In [31]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]:  [0 1 2 3]
a[1]:  [4 5 6 7]
a[2]:  [ 8  9 10 11]


In [32]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

for data in a:
    print(data)

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [33]:

a = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{a}\n")

print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
print(a[2, 0], a[2, 1], a[2, 2])

a = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{a}\n")

print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[1][2])
print(a[2][0], a[2][1], a[2][2])


ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8
ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8


In [34]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")
print("a[0, 1:] : ", a[0, 1:])
print("a[1, :3] : ", a[1, :3])
print("a[2, 1:3] : ", a[2, 1:3])


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0, 1:] :  [1 2 3]
a[1, :3] :  [4 5 6]
a[2, 1:3] :  [ 9 10]


In [35]:

a = np.arange(12).reshape((4, 3))
print(f"ndarray: \n{a}\n")
print("a[1:, 0] : ", a[1:, 0])
print("a[:3, 1] : ", a[:3, 1])
print("a[1:3, 2] : ", a[1:3, 2])

ndarray: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

a[1:, 0] :  [3 6 9]
a[:3, 1] :  [1 4 7]
a[1:3, 2] :  [5 8]


In [36]:

a = np.arange(16).reshape((4, 4))
print(f"ndarray: \n{a}\n")
print("a[1:3, 1:3] : \n", a[1:3, 1:3])
print("a[:2, :3] : \n", a[:2, :3])
print("a[1:, 2:] : \n", a[1:, 2:])
print("a[2:, :-2] : \n", a[2:, :-2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[1:3, 1:3] : 
 [[ 5  6]
 [ 9 10]]
a[:2, :3] : 
 [[0 1 2]
 [4 5 6]]
a[1:, 2:] : 
 [[ 6  7]
 [10 11]
 [14 15]]
a[2:, :-2] : 
 [[ 8  9]
 [12 13]]


In [37]:
image = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{image}\n")

horizontal_flip = image[:, ::-1]
print(f"horizontal_flip: \n{horizontal_flip}\n")

vertical_flip = image[::-1, :]
print(f"vertical_flip: \n{vertical_flip}\n")

rotation = image[::-1, ::-1]
print(f"rotation: \n{rotation}\n")


ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

horizontal_flip: 
[[2 1 0]
 [5 4 3]
 [8 7 6]]

vertical_flip: 
[[6 7 8]
 [3 4 5]
 [0 1 2]]

rotation: 
[[8 7 6]
 [5 4 3]
 [2 1 0]]



In [38]:
a = np.arange(16).reshape((4, 4))
print(f"ndarray: \n{a}\n")
print("a[0, :] : \n", a[0, :])
print("a[0, ...] : \n", a[0, ...])
print("a[:, 1] : \n", a[:, 1])
print("a[..., 1] : \n", a[..., 1])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[0, :] : 
 [0 1 2 3]
a[0, ...] : 
 [0 1 2 3]
a[:, 1] : 
 [ 1  5  9 13]
a[..., 1] : 
 [ 1  5  9 13]


In [39]:
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[0] : \n", a[0])
print("a[1] : \n", a[1])
print("a[2] : \n", a[2])

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0] : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a[1] : 
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
a[2] : 
 [[18 19 20]
 [21 22 23]
 [24 25 26]]


In [40]:

a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[0, 0] : \n", a[0, 0])
print("a[0, 1] : \n", a[0, 1])
print("a[0, 2] : \n", a[0, 2], '\n')
print("a[1, 0] : \n", a[1, 0])
print("a[1, 1] : \n", a[1, 1])
print("a[1, 2] : \n", a[1, 2], '\n')
print("a[2, 0] : \n", a[2, 0])
print("a[2, 1] : \n", a[2, 1])
print("a[2, 2] : \n", a[2, 2])

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0, 0] : 
 [0 1 2]
a[0, 1] : 
 [3 4 5]
a[0, 2] : 
 [6 7 8] 

a[1, 0] : 
 [ 9 10 11]
a[1, 1] : 
 [12 13 14]
a[1, 2] : 
 [15 16 17] 

a[2, 0] : 
 [18 19 20]
a[2, 1] : 
 [21 22 23]
a[2, 2] : 
 [24 25 26]


In [41]:

a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[0, :2, :2] : \n", a[0, :2, :2])
print("a[1, :2, :] : \n", a[1, :2, :])
print("a[2, -2:, -2:] : \n", a[2, -2:, -2:])


ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0, :2, :2] : 
 [[0 1]
 [3 4]]
a[1, :2, :] : 
 [[ 9 10 11]
 [12 13 14]]
a[2, -2:, -2:] : 
 [[22 23]
 [25 26]]


In [42]:
images = np.random.normal(size=(32, 100, 200))
print("image set: ", images.shape)

image0 = images[0, :, :]
image0 = images[0, ...]
print(image0.shape)

image set:  (32, 100, 200)
(100, 200)


In [43]:

images = np.random.normal(size=(32, 100, 200))
print("image set: ", images.shape)

col0 = images[:, :, 0]
print(col0.shape)

col0 = images[..., 0]
print(col0.shape, '\n')

image0_col0 = images[0, :, 0]
print(image0_col0.shape)

image0_col0 = images[0, ..., 0]
print(image0_col0.shape)


image set:  (32, 100, 200)
(32, 100)
(32, 100) 

(100,)
(100,)


In [44]:

a = np.arange(3*3*3).reshape((3, 3, 3))

print("a[:, :2, :] : \n", a[:, :2, :])

print(f"ndarray: \n{a}\n")


a[:, :2, :] : 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [45]:
a = np.arange(3*3*3).reshape((3, 3, 3))
print("a[:, :, 0] : \n", a[:, :, 0])
print(f"ndarray: \n{a}\n")

a[:, :, 0] : 
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [46]:
import numpy as npprint
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [47]:
image = np.random.normal(size=(3, 500, 300))
image_r = image[0]
image_g = image[1]
image_b = image[2]
image_r, image_g, image_b = image
print(image_r.shape, image_g.shape, image_b.shape)

(500, 300) (500, 300) (500, 300)


In [48]:

image = np.random.normal(size=(3, 500, 300))
top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]
print(top_left.shape, top_right.shape)
print(bottom_left.shape, bottom_right.shape)


(3, 100, 100) (3, 100, 100)
(3, 100, 100) (3, 100, 100)


In [49]:
a = np.arange(10)
indices = np.array([0, 3, 4])
print(a[indices])
print(f"ndarray: \n{a}\n")

[0 3 4]
ndarray: 
[0 1 2 3 4 5 6 7 8 9]



In [50]:
a = np.arange(10)
indices = np.array([0, 0, 5, 5])
print(a[indices])

print(f"ndarray: \n{a}\n")

[0 0 5 5]
ndarray: 
[0 1 2 3 4 5 6 7 8 9]



In [51]:
a = np.arange(10)
indices = np.array([[1, 2, 3], [5, 8, 9]])
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")
print(f"ndarray: \n{a}\n")

indices: 
[[1 2 3]
 [5 8 9]]
a[indices]: 
[[1 2 3]
 [5 8 9]]
ndarray: 
[0 1 2 3 4 5 6 7 8 9]



In [52]:
a = np.random.randint(0, 20, (10, ))
print(f"ndarray: \n{a}\n")

indices = np.random.randint(0, 10, size=(2, 3, 4))
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[19 15  5 12  5 10 13  1  7 13]

indices: 
[[[5 1 3 3]
  [5 1 4 8]
  [3 2 2 9]]

 [[1 1 8 2]
  [9 4 1 1]
  [5 5 5 5]]]
a[indices]: 
[[[10 15 12 12]
  [10 15  5  7]
  [12  5  5 13]]

 [[15 15  7  5]
  [13  5 15 15]
  [10 10 10 10]]]


In [53]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")
print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]:  [0 1 2 3]
a[1]:  [4 5 6 7]
a[2]:  [ 8  9 10 11]


In [54]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([0, 2])
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 2]
a[indices]: 
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [55]:

a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([0, 0, 1, 1, 2, 2])

print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 0 1 1 2 2]
a[indices]: 
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]


In [56]:

a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([[0, 1, 2], [-3, -2, -1]])

print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[[ 0  1  2]
 [-3 -2 -1]]
a[indices]: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [57]:

a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices0, indices1 = np.array([0]), np.array([0])
print(a[indices0, indices1])
indices0, indices1 = np.array([1]), np.array([2])
print(a[indices0, indices1])

indices0, indices1 = np.array([-1]), np.array([0])
print(a[indices0, indices1])

indices0, indices1 = np.array([-1]), np.array([-1])
print(a[indices0, indices1])


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0]
[6]
[8]
[11]


In [58]:
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices0, indices1 = np.array([0, 1, 2]), np.array([1, 2, 3])

print("Paired indices")
for idx0, idx1 in zip(indices0, indices1):
    print(f"({idx0}, {idx1})")
print(f"a[indices0, indices1]: \n{a[indices0, indices1]}")

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Paired indices
(0, 1)
(1, 2)
(2, 3)
a[indices0, indices1]: 
[ 1  6 11]


In [59]:

a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices0 = np.array([[0, 1, 2], [0, 1, 2]])
indices1 = np.array([[0, 1, 2], [1, 2, 3]])
print("Paired indices")

for row_indices0, row_indices1 in zip(indices0, indices1):
    for idx0, idx1 in zip(row_indices0, row_indices1):
        print(f"({idx0}, {idx1})", end=' ')
        print()

print(f"a[indices0, indices1]: \n{a[indices0, indices1]}")


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Paired indices
(0, 0) 
(1, 1) 
(2, 2) 
(0, 1) 
(1, 2) 
(2, 3) 
a[indices0, indices1]: 
[[ 0  5 10]
 [ 1  6 11]]


In [60]:

a = np.arange(5)
print(f"ndarray: \n{a}")

b_indices = np.array([True, False, True, False, True])

print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")


ndarray: 
[0 1 2 3 4]
b_indices: 
[ True False  True False  True]

a[b_indices]: 
[0 2 4]


In [61]:
a = np.random.randint(0, 20, (10, ))
print(f"ndarray: \n{a}")

b_indices = (a % 2 == 0)
print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")


ndarray: 
[ 0 16  1  4  3 11  6 18  3  4]
b_indices: 
[ True  True False  True False False  True  True False  True]

a[b_indices]: 
[ 0 16  4  6 18  4]


In [62]:
a = np.random.randint(0, 20, (2, 2))
print(f"ndarray: \n{a}")

b_indices = np.array([[True, False],
[False, True]])

print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[[11  5]
 [ 0 18]]
b_indices: 
[[ True False]
 [False  True]]

a[b_indices]: 
[11 18]


In [63]:

a = np.random.randint(0, 20, (3, 4))
print(f"ndarray: \n{a}")
b_indices = (a > 10)

print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")



ndarray: 
[[ 0 12 15 17]
 [18 12  5 14]
 [14  6 18 13]]
b_indices: 
[[False  True  True  True]
 [ True  True False  True]
 [ True False  True  True]]

a[b_indices]: 
[12 15 17 18 12 14 14 18 13]


In [64]:

a = np.array([True, False, True, False])
nonzero = np.nonzero(a)
a = np.array([[True, False],[True, False]])
where = np.where(a)


print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}")
print(f"where: \n{where}")


print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}")
print(f"where: \n{where}")

nonzero = np.nonzero(a)
where = np.where(a)

a: 
[[ True False]
 [ True False]]

nonzero: 
(array([0, 2], dtype=int64),)
where: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))
a: 
[[ True False]
 [ True False]]

nonzero: 
(array([0, 2], dtype=int64),)
where: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))


In [65]:
a = np.array([[[True, False, True],
[True, False, False]],
[[False, True, False],
[True, False, True]]])
nonzero = np.nonzero(a)
where = np.where(a)

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}")
print(f"where: \n{where}")


a: 
[[[ True False  True]
  [ True False False]]

 [[False  True False]
  [ True False  True]]]

nonzero: 
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 0, 1, 0, 1, 1], dtype=int64), array([0, 2, 0, 1, 0, 2], dtype=int64))
where: 
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 0, 1, 0, 1, 1], dtype=int64), array([0, 2, 0, 1, 0, 2], dtype=int64))


In [66]:

a = np.random.randint(-2, 3, size=(3, 3))
u_nonzero = a[np.nonzero(a)]
u_where = a[np.where(a)]
u_bool = a[a != 0]
print(f"a: \n{a}\n")
print(f"using nonzero: \n{u_nonzero}")
print(f"using where: \n{u_where}")
print(f"using bool ndarray: \n{u_bool}")

a: 
[[ 1  1 -2]
 [ 2 -1  2]
 [-2 -1 -1]]

using nonzero: 
[ 1  1 -2  2 -1  2 -2 -1 -1]
using where: 
[ 1  1 -2  2 -1  2 -2 -1 -1]
using bool ndarray: 
[ 1  1 -2  2 -1  2 -2 -1 -1]


In [67]:

a = np.random.randint(-2, 3, size=(3, 3))

u_nonzero = a[np.nonzero(a > 0)]
u_where = a[np.where(a > 0)]
u_bool = a[a > 0]
print(f"a: \n{a}\n")
print(f"using nonzero: \n{u_nonzero}")
print(f"using where: \n{u_where}")
print(f"using bool ndarray: \n{u_bool}")


a: 
[[ 1  0  0]
 [-2  0  2]
 [ 1 -2  0]]

using nonzero: 
[1 2 1]
using where: 
[1 2 1]
using bool ndarray: 
[1 2 1]


In [68]:
a = np.arange(5)
print("ndarray: ", a)
print("np.sum: ", np.sum(a))
print("ndarray.sum: ", a.sum())

ndarray:  [0 1 2 3 4]
np.sum:  10
ndarray.sum:  10


In [69]:

a = np.arange(6).reshape((2, -1))
print("ndarray: \n", a)
print("np.sum: ", np.sum(a))
print("ndarray.sum: ", a.sum())


ndarray: 
 [[0 1 2]
 [3 4 5]]
np.sum:  15
ndarray.sum:  15


In [70]:

a = np.arange(12).reshape((3, -1))
sum_ = a.sum(axis=0)
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=0): {}\n{}".format(sum_.shape, sum_))


ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndarray.sum(axis=0): (4,)
[12 15 18 21]


In [71]:

a = np.arange(12).reshape((3, -1))
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=1): {}\n{}".format(sum_.shape, sum_))

ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndarray.sum(axis=1): (4,)
[12 15 18 21]


In [72]:

a = np.arange(12).reshape((3, -1))
sum_class = np.sum(a, axis=0)
sum_student = np.sum(a, axis=1)
print("scores: {}\n{}".format(a.shape, a))
print("sum_class: {}\n{}".format(sum_class.shape,
sum_class))
print("sum_student: {}\n{}".format(sum_student.shape,
sum_student))


scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class: (4,)
[12 15 18 21]
sum_student: (3,)
[ 6 22 38]


In [73]:

a = np.arange(12).reshape((3, -1))
sum_class = np.sum(a, axis=0, keepdims=True)
sum_student = np.sum(a, axis=1, keepdims=True)
print("scores: {}\n{}".format(a.shape, a))
print("sum_class: {}\n{}".format(sum_class.shape,
sum_class))
print("sum_student: {}\n{}".format(sum_student.shape,
sum_student))

scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class: (1, 4)
[[12 15 18 21]]
sum_student: (3, 1)
[[ 6]
 [22]
 [38]]


In [74]:

n_student, n_class = 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score,
high=M_score,
size=(n_student,n_class))

mean_class = np.mean(scores, axis=0, keepdims=True)
mean_student = np.mean(scores, axis=1, keepdims=True)
print("Shapes: ")
print(scores.shape, mean_class.shape, mean_student.shape, '\n')
print("Mean subtraction by classes\n", scores - mean_class)
print("Mean subtraction by students\n", scores - mean_student)

Shapes: 
(3, 4) (1, 4) (3, 1) 

Mean subtraction by classes
 [[-17.         -44.         -41.33333333  26.        ]
 [-14.          48.          51.66666667 -54.        ]
 [ 31.          -4.         -10.33333333  28.        ]]
Mean subtraction by students
 [[  4.   -27.   -34.    57.  ]
 [-20.    38.    32.   -50.  ]
 [ 21.75 -17.25 -33.25  28.75]]


In [75]:

a = np.arange(2*3*4).reshape((2, 3, 4))

sum_ = a.sum(axis=0)
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=0): {}\n{}".format(sum_.shape, sum_))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
ndarray.sum(axis=0): (3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [76]:

a = np.arange(2*3*4).reshape((2, 3, 4))

sum_ = a.sum(axis=1)
sum_k = a.sum(axis=1, keepdims=True)
print("ndarray: {}\n{}".format(a.shape, a))
print("axis=1: {}\n{}".format(sum_.shape, sum_))
print("axis=1, keepdims=True: {}\n{}".format(sum_k.shape,sum_k))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
axis=1: (2, 4)
[[12 15 18 21]
 [48 51 54 57]]
axis=1, keepdims=True: (2, 1, 4)
[[[12 15 18 21]]

 [[48 51 54 57]]]


In [77]:

a = np.arange(2*3*4).reshape((2, 3, 4))

sum_ = a.sum(axis=2)
sum_k = a.sum(axis=2, keepdims=True)
print("ndarray: {}\n{}".format(a.shape, a))
print("axis=2: {}\n{}".format(sum_.shape, sum_))
print("axis=2, keepdims=True: {}\n{}".format(sum_k.shape,sum_k))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
axis=2: (2, 3)
[[ 6 22 38]
 [54 70 86]]
axis=2, keepdims=True: (2, 3, 1)
[[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]


In [78]:

import numpy as np
n_test_time, n_student, n_class = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score,high=M_score,size=(n_test_time,n_student,n_class))
print("scores: \n", scores)

score_mean = np.mean(scores, axis=0)
print("score mean: ",score_mean.shape, '\n',score_mean)

score_mean = np.mean(scores, axis=1)
print("score mean: ",score_mean.shape, '\n',score_mean)


scores: 
 [[[93 64 67 83]
  [19 14 42 35]
  [63 90 20 16]]

 [[68 19 26 75]
  [54 19 78 55]
  [ 6 85 83 52]]

 [[33 53 60 73]
  [86 48 56 44]
  [ 2 99 69 60]]

 [[36  2 21  9]
  [30 96 80 60]
  [75 40 37 60]]]
score mean:  (3, 4) 
 [[57.5  34.5  43.5  60.  ]
 [47.25 44.25 64.   48.5 ]
 [36.5  78.5  52.25 47.  ]]
score mean:  (4, 4) 
 [[58.33333333 56.         43.         44.66666667]
 [42.66666667 41.         62.33333333 60.66666667]
 [40.33333333 66.66666667 61.66666667 59.        ]
 [47.         46.         46.         43.        ]]


In [79]:

C, H, W = 3, 100, 200
# (C, H, W) case
images = np.random.randint(0, 256,size=(C, H, W))
print("Shape of original image:", images.shape)

gray_image = np.mean(images, axis=0)
print("Shape of gray-scaled image:", gray_image.shape, '\n')

gray_image = np.mean(images, axis=-1)
print("Shape of gray-scaled image:", gray_image.shape)

# (H, W, C) case
images = np.random.randint(0, 256,size=(H, W, C))
print("Shape of original image:", images.shape)


Shape of original image: (3, 100, 200)
Shape of gray-scaled image: (100, 200) 

Shape of gray-scaled image: (3, 100)
Shape of original image: (100, 200, 3)


In [80]:

import numpy as np
a = np.arange(3*3).reshape((3, 3))
cumsum = np.cumsum(a)

print("cumsum: {}\n{}".format(cumsum.shape, cumsum))
print("ndarray: {}\n{}".format(a.shape, a))


cumsum: (9,)
[ 0  1  3  6 10 15 21 28 36]
ndarray: (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:

import numpy as np
a = np.arange(2*3*4).reshape((2, 3, 4))
cumsum = np.cumsum(a)

print("cumsum: {}\n{}".format(cumsum.shape, cumsum))
print("ndarray: {}\n{}".format(a.shape, a))


cumsum: (24,)
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276]
ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [82]:
a = np.arange(3*4).reshape((3, 4))
print("ndarray: {}\n{}".format(a.shape, a))

cumsum = np.cumsum(a, axis=1)
cumsum = np.cumsum(a, axis=0)

print("cumsum: {}\n{}"\
.format(cumsum.shape,
cumsum))
print("cumsum: {}\n{}"\
.format(cumsum.shape,
cumsum))

ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
cumsum: (3, 4)
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
cumsum: (3, 4)
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [83]:
a = np.arange(1, 5)
print("ndarray: {}\n{}\n".format(a.shape, a))

prod = np.prod(a)
cumprod = np.cumprod(a)
print("prod: {}\n{}".format(prod.shape, prod))
print("cumprod: {}\n{}".format(cumprod.shape, cumprod))

ndarray: (4,)
[1 2 3 4]

prod: ()
24
cumprod: (4,)
[ 1  2  6 24]


In [84]:

a = np.arange(1, 1+12).reshape((3, 4))
print("ndarray: {}\n{}\n".format(a.shape, a))

cumprod = np.cumprod(a, axis=0)
print("prod(axis=0): {}\n{}".format(prod.shape, prod))
print("cumprod(axis=0): {}\n{}".format(cumprod.shape, cumprod))

ndarray: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

prod(axis=0): ()
24
cumprod(axis=0): (3, 4)
[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]


In [85]:

a = np.random.randint(0, 10, (5, ))
print("ndarray: {}\n{}\n".format(a.shape, a))

diff = np.diff(a)
print("diff: {}\n{}".format(diff.shape, diff))

ndarray: (5,)
[6 1 6 5 8]

diff: (4,)
[-5  5 -1  3]


In [86]:

np.random.seed(0)
a = np.random.randint(0, 10, (4, 4))
print("ndarray: {}\n{}\n".format(a.shape, a))
diff = np.diff(a, axis=0) 

print("diff: {}\n{}"\
.format(diff.shape,
diff))

diff = np.diff(a, axis=1)
print("diff: {}\n{}"\
.format(diff.shape,
diff))

ndarray: (4, 4)
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]

diff: (3, 4)
[[ 2  9  0  2]
 [-5 -5  4  1]
 [ 6  4 -6  0]]
diff: (4, 3)
[[-5  3  0]
 [ 2 -6  2]
 [ 2  3 -1]
 [ 0 -7  5]]


In [87]:

np.random.seed(0)

x = np.random.randint(1, 10, (5,))
w = np.array([1, 2, 3, 4, 5])
print(np.average(x, weights=w))
print(np.sum(w*x)/np.sum(w)) 

5.066666666666666
5.066666666666666


In [88]:

#numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

x = np.arange(9)
median = np.median(x)
print(x)
print(median)

x = np.arange(10)
median = np.median(x)
print(x)
print(median)

[0 1 2 3 4 5 6 7 8]
4.0
[0 1 2 3 4 5 6 7 8 9]
4.5


In [89]:

x = np.random.randint(1, 10, (100,))
mean = np.mean(x)
median = np.median(x)
print("mean/median: {} / {}".format(mean, median))

x = np.append(x, 1000)
mean = np.mean(x)
median = np.median(x)
print("mean/median: {} / {}".format(mean, median))



mean/median: 4.66 / 4.0
mean/median: 14.514851485148515 / 4.0


In [90]:

#numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
#ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

#numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
#ndarray.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)
var = scores.var()
std = scores.std()
print("variance: ", var)
print("standard deviation: ", std, '\n')
print("square of std: ", std**2)
print("square root of var: ", var**0.5)


variance:  734.4578993055557
standard deviation:  27.100883736615597 

square of std:  734.4578993055558
square root of var:  27.100883736615597


In [91]:



means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3
scores = np.random.normal(loc=means,
scale=stds,
size=(n_student, n_class))
scores = scores.astype(np.float32)
print("shape of scores: ", scores.shape)
print("dtype of scores: ", scores.dtype)

print("means before stdz: \n", means)
print("stds before stdz: \n", stds, '\n')


score_stdz = (scores - means)/stds # standardization
means_stdz = score_stdz.mean(axis=0)
stds_stdz = score_stdz.std(axis=0)

means = scores.mean(axis=0)
stds = scores.std(axis=0)
print("means after stdz: \n", means_stdz)
print("stds after stdz: \n", stds_stdz)


shape of scores:  (100, 3)
dtype of scores:  float32
means before stdz: 
 [50, 60, 70]
stds before stdz: 
 [3, 5, 10] 

means after stdz: 
 [-0.0846136  -0.08142226  0.06996149]
stds after stdz: 
 [1.10905147 1.01120431 0.91903899]


In [92]:

#numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
#ndarray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
#numpy.argmax(a, axis=None, out=None)
#ndarray.argmax(axis=None, out=None)

a = np.random.randint(0, 100, (10, ))
M = np.max(a)
M_idx = np.argmax(a)
print(f"ndarray: \n{a}")
print(f"M/M_idx: {M}/{M_idx}")

ndarray: 
[29 12 46 32 34 87 25 46 52 64]
M/M_idx: 87/5


In [93]:
means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3
scores = np.random.normal(loc=means,
scale=stds,
size=(n_student, n_class))
scores = scores.astype(np.float32)
scores_max = np.max(scores, axis=0)
scores_max_idx = np.argmax(scores, axis=0)
print("Max scores: ", scores_max)
print("Max indices: ", scores_max_idx)
scores_max_idx = np.argmax(scores, axis=1)
print("Max subjects: ", scores_max_idx)


Max scores:  [56.26657  69.762634 91.0188  ]
Max indices:  [13 39 68]
Max subjects:  [1 2 2 2 2 2 1 2 1 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 1 1 1 2 2
 1 2 1 2 2 2 1 2 2 2 2 1 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 2 2 2 1 2 2]


In [94]:
means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3
scores = np.random.normal(loc=means,
scale=stds,
size=(n_student, n_class))
scores = scores.astype(np.float32)

scores_max = np.amax(scores, axis=0)
scores_min = np.amin(scores, axis=0)
scores_mM_norm = (scores - scores_min)/(scores_max - scores_min)
scores_max = np.amax(scores_mM_norm, axis=0)
scores_min = np.amin(scores_mM_norm, axis=0)
print(f"Max scores: {scores_max}")
print(f"min scores: {scores_min}")

Max scores: [1. 1. 1.]
min scores: [0. 0. 0.]


In [95]:

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

maximum = np.maximum(u, v)
minimum = np.minimum(u, v)

print(f"maximum: {maximum.shape}\n{maximum}")
print(f"minimum: {minimum.shape}\n{minimum}")

u: (10,)
[2 1 7 0 2 9 3 4 9 3]
v: (10,)
[0 0 6 4 3 3 1 0 7 8]

maximum: (10,)
[2 1 7 4 3 9 3 4 9 8]
minimum: (10,)
[0 0 6 0 2 3 1 0 7 3]


In [96]:

u = np.random.randint(0, 10, (3, 4))
v = np.random.randint(0, 10, (3, 4))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

maximum = np.maximum(u, v)
minimum = np.minimum(u, v)

print(f"maximum: {maximum.shape}\n{maximum}")
print(f"minimum: {minimum.shape}\n{minimum}")

u: (3, 4)
[[6 2 8 8]
 [9 6 4 1]
 [8 5 4 3]]
v: (3, 4)
[[5 7 6 6]
 [9 3 3 2]
 [7 3 9 9]]

maximum: (3, 4)
[[6 7 8 8]
 [9 6 4 2]
 [8 5 9 9]]
minimum: (3, 4)
[[5 2 6 6]
 [9 3 3 1]
 [7 3 4 3]]


In [97]:

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

up_vals = np.full_like(u, fill_value=100)
down_vals = np.full_like(u, fill_value=-100)
print(np.where(u > v, up_vals, down_vals))


u: (10,)
[5 9 8 3 8 5 9 0 7 0]
v: (10,)
[1 6 6 4 5 7 6 0 1 6]

[ 100  100  100 -100  100 -100  100 -100  100 -100]


In [98]:

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

maximum = np.maximum(u, v)
maximum_where = np.where(u > v, u, v)
print(f"maximum: {maximum.shape}\n{maximum}")
print(f"maximum(where): {maximum_where.shape}\n{maximum_where}")


u: (10,)
[6 4 2 2 4 4 3 1 0 6]
v: (10,)
[6 0 9 8 9 5 2 9 8 4]

maximum: (10,)
[6 4 9 8 9 5 3 9 8 6]
maximum(where): (10,)
[6 4 9 8 9 5 3 9 8 6]


In [99]:

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

minimum = np.minimum(u, v)
minimum_where = np.where(u > v, v, u)
minimum_where2 = np.where(u < v, u, v)
print(f"minimum: {minimum.shape}\n{minimum}")
print(f"minimum(where): {minimum_where.shape}\n{minimum_where}")
print(f"minimum(where): {minimum_where2.shape}\n{minimum_where2}")


u: (10,)
[4 0 2 5 7 7 1 3 2 0]
v: (10,)
[3 2 2 2 3 5 1 7 5 3]

minimum: (10,)
[3 0 2 2 3 5 1 3 2 0]
minimum(where): (10,)
[3 0 2 2 3 5 1 3 2 0]
minimum(where): (10,)
[3 0 2 2 3 5 1 3 2 0]


In [100]:

#numpy.around(a, decimals=0, out=None)
#numpy.round_(a, decimals=0, out=None)
#ndarray.round(decimals=0, out=None)

x = np.random.uniform(-5, 5, (5, ))

np_around = np.around(x, decimals=2)
np_round_ = np.round_(x, decimals=2)
x_round = x.round(decimals=2)
print(f"x: \n {x}\n")
print(f"np_around: \n {np_around}")
print(f"np_round_: \n {np_round_}")
print(f"x_round: \n {x_round}")

x: 
 [ 0.49237259  1.43198776  0.70423411 -2.26322451 -2.79175716]

np_around: 
 [ 0.49  1.43  0.7  -2.26 -2.79]
np_round_: 
 [ 0.49  1.43  0.7  -2.26 -2.79]
x_round: 
 [ 0.49  1.43  0.7  -2.26 -2.79]


In [101]:

x = np.random.uniform(-5, 5, (5, ))
np_around = np.around(x)
np_round_ = np.round_(x)
x_round = x.round()
print(f"x: \n {x}\n")
print(f"np_around: \n {np_around}")
print(f"np_round_: \n {np_round_}")
print(f"x_round: \n {x_round}")


x: 
 [-3.46417488  2.59873241  2.92718364  0.50337732  0.32325623]

np_around: 
 [-3.  3.  3.  1.  0.]
np_round_: 
 [-3.  3.  3.  1.  0.]
x_round: 
 [-3.  3.  3.  1.  0.]


In [102]:
x = np.random.uniform(-5, 5, (5, ))
trunc = np.trunc(x)
print(f"x: \n {x}\n")
print(f"trunc: \n {trunc}")

x: 
 [-1.38893522 -4.24149908  4.84030301  3.69848071 -2.94500873]

trunc: 
 [-1. -4.  4.  3. -2.]


In [103]:

x = np.random.uniform(-5, 5, (5, ))
trunc_where = np.where(x >= 0, np.floor(x), np.ceil(x))
trunc = np.trunc(x)
print(f"x: \n {x}\n")
print(f"trunc_where: \n {trunc_where}")
print(f"trunc: \n{trunc}")

x: 
 [-0.75147361  1.52514346  0.5264587  -2.48799883 -1.75947679]

trunc_where: 
 [-0.  1.  0. -2. -1.]
trunc: 
[-0.  1.  0. -2. -1.]


In [104]:

x = np.random.uniform(-5, 5, (5, ))
trunc = 0.1*np.trunc(10*x)
print(f"x: \n {x}\n")
print(f"trunc: \n {trunc}")

x: 
 [ 2.88164612 -3.37549269 -4.18418896  0.13184716 -2.78670248]

trunc: 
 [ 2.8 -3.3 -4.1  0.1 -2.7]


In [105]:

x = np.random.uniform(-5, 5, (5, ))
int_part = np.trunc(x)
frac_part = x - int_part
print(f"x: \n {x}\n")
print(f"int_part: \n {int_part}")
print(f"frac_part: \n {frac_part}")

x: 
 [-2.676835    0.2591664  -0.01466451  4.27958364  0.03449278]

int_part: 
 [-2.  0. -0.  4.  0.]
frac_part: 
 [-0.676835    0.2591664  -0.01466451  0.27958364  0.03449278]


In [106]:

x = np.random.randint(0, 100, (10, ))
sort = np.sort(x)
argsort = np.argsort(x)
print(f"x: \n{x}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[43 67 20 91 92 14 14 80 99 63]

sort: 
[14 14 20 43 63 67 80 91 92 99]
argsort: 
[5 6 2 0 9 1 7 3 4 8]


In [107]:

x = np.random.randint(0, 100, (10, ))
sort = np.sort(x)[::-1]
argsort = np.argsort(x)[::-1]
print(f"x: \n{x}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")


x: 
[43 27 87 20 23 34 32 65 22 21]

sort: 
[87 65 43 34 32 27 23 22 21 20]
argsort: 
[2 7 0 5 6 1 4 8 9 3]


In [108]:

pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()
top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]
print(f"pred: \n{pred.round(3)}\n")
print(f"top-3 pred: {top3_pred.round(3)}")
print(f"top-3 indices: {top3_indices}")


pred: 
[0.309 0.04  0.042 0.199 0.41 ]

top-3 pred: [0.41  0.309 0.199]
top-3 indices: [4 0 3]


In [109]:

x = np.random.randint(0, 100, (4, 5))
sort = np.sort(x, axis=0)
argsort = np.argsort(x, axis=0)
print(f"x: \n{x}\n")
print(f"argsort: \n{argsort}")
print(f"sort: \n{sort}")

x: 
[[ 8  5 97 86 82]
 [10 62 29 11 30]
 [71 58 94 42 85]
 [71 25 54 83 25]]

argsort: 
[[0 0 1 1 3]
 [1 3 3 2 1]
 [2 2 2 3 0]
 [3 1 0 0 2]]
sort: 
[[ 8  5 29 11 25]
 [10 25 54 42 30]
 [71 58 94 83 82]
 [71 62 97 86 85]]


In [110]:

x = np.random.randint(0, 100, (4, 5))

sort = np.sort(x, axis=0)[::-1, :]
argsort = np.argsort(x, axis=0)[::-1, :]
print(f"x: \n{x}\n")
print(f"sort: \n{sort}")

print(f"argsort: \n{argsort}")


x: 
[[45  3 84 83 37]
 [33 60 89  7 60]
 [37 84 98 16 45]
 [39 33 97 65 73]]

sort: 
[[45 84 98 83 73]
 [39 60 97 65 60]
 [37 33 89 16 45]
 [33  3 84  7 37]]
argsort: 
[[0 2 2 0 3]
 [3 1 3 3 1]
 [2 3 1 2 2]
 [1 0 0 1 0]]


In [111]:

scores = np.random.randint(0, 100, (5, 3))
sort = np.sort(scores, axis=0)[::-1, :]
argsort = np.argsort(scores, axis=0)[::-1, :]
top2_scores = sort[:2, :]
top2_students = argsort[:2, :]
print(f"scores: \n{scores}\n")
print(f"top-2 scores: \n{top2_scores}")
print(f"top-2 students: \n{top2_students}")

print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}\n")


scores: 
[[87 68 24]
 [ 6 97 60]
 [88 61 59]
 [74 29 28]
 [24  3 82]]

top-2 scores: 
[[88 97 82]
 [87 68 60]]
top-2 students: 
[[2 1 4]
 [0 0 1]]
sort: 
[[88 97 82]
 [87 68 60]
 [74 61 59]
 [24 29 28]
 [ 6  3 24]]
argsort: 
[[2 1 4]
 [0 0 1]
 [3 2 2]
 [4 3 3]
 [1 4 0]]



In [112]:

x = np.random.randint(0, 100, (4, 5))
sort_ascending = np.sort(x, axis=1)
argsort_ascending = np.argsort(x, axis=1)
sort_descending = np.sort(x, axis=1)[:, ::-1]
argsort_descending = np.argsort(x, axis=1)[:, ::-1]
print(f"x: \n{x}\n")
print(f"sort(ascending): \n{sort_ascending}")
print(f"argsort(ascending): \n{argsort_ascending}\n")
print(f"sort(descending): \n{sort_descending}")
print(f"argsort(descending): \n{argsort_descending}\n")


x: 
[[21  6 84 21 27]
 [26 89 64  3 53]
 [37  7 80 75 11]
 [ 2 54  5 17 78]]

sort(ascending): 
[[ 6 21 21 27 84]
 [ 3 26 53 64 89]
 [ 7 11 37 75 80]
 [ 2  5 17 54 78]]
argsort(ascending): 
[[1 0 3 4 2]
 [3 0 4 2 1]
 [1 4 0 3 2]
 [0 2 3 1 4]]

sort(descending): 
[[84 27 21 21  6]
 [89 64 53 26  3]
 [80 75 37 11  7]
 [78 54 17  5  2]]
argsort(descending): 
[[2 4 3 0 1]
 [1 2 4 0 3]
 [2 3 0 4 1]
 [4 1 3 2 0]]



In [113]:

scores = np.random.randint(0, 100, (5, 3))
sort = np.sort(scores, axis=1)
argsort = np.argsort(scores, axis=1)
bottom2_scores = sort[:, :2]
bottom2_subjects = argsort[:, :2]
print(f"scores: \n{scores}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}\n")
print(f"bottom-2 scores: \n{bottom2_scores}")
print(f"bottom-2 subjects: \n{bottom2_subjects}")

scores: 
[[ 5 78 81]
 [30 98  3]
 [ 0 93 44]
 [44 61  0]
 [17 29 91]]

sort: 
[[ 5 78 81]
 [ 3 30 98]
 [ 0 44 93]
 [ 0 44 61]
 [17 29 91]]
argsort: 
[[0 1 2]
 [2 0 1]
 [0 2 1]
 [2 0 1]
 [0 1 2]]

bottom-2 scores: 
[[ 5 78]
 [ 3 30]
 [ 0 44]
 [ 0 44]
 [17 29]]
bottom-2 subjects: 
[[0 1]
 [2 0]
 [0 2]
 [2 0]
 [0 1]]
